/**
 * Standardized system message types for Regaged.
 * Shared across game modes (Fastings, Castings, etc.).
 * System messages are only generated by the server/game engine.
 */
export type SystemMessageType =
  | "DAY_CHANGE"
  | "NOMINATION"
  | "VOTE_RESULT"
  | "PLAYER_ELIMINATED"
  | "DROP_SPAWN"
  | "HEALTH_CHANGE"
  | "POV_RESULT"
  | "GAME_FINISHED";

export interface BaseSystemPayload {
  type: SystemMessageType;
}

export interface DayChangePayload extends BaseSystemPayload {
  type: "DAY_CHANGE";
  dayNumber: number;
  phase?: "nominate" | "vote";
}

export interface NominationPayload extends BaseSystemPayload {
  type: "NOMINATION";
  dayNumber?: number;
  roundNumber?: number;
  nominees: { playerId: string; username?: string; votes?: number }[];
}

export interface VoteResultPayload extends BaseSystemPayload {
  type: "VOTE_RESULT";
  dayNumber?: number;
  roundNumber?: number;
  results: { playerId: string; username?: string; votes: number; tag?: string }[];
}

export interface PlayerEliminatedPayload extends BaseSystemPayload {
  type: "PLAYER_ELIMINATED";
  playerId: string;
  username?: string;
  votes?: number;
  dayNumber?: number;
}

export interface DropSpawnPayload extends BaseSystemPayload {
  type: "DROP_SPAWN";
  eventId: string;
  options: { slotIndex: number; kind: "APPLE" | "KEY" | "POISON" }[];
}

export interface HealthChangePayload extends BaseSystemPayload {
  type: "HEALTH_CHANGE";
  playerId: string;
  delta: number;
  reason?: string;
}

export interface PovResultPayload extends BaseSystemPayload {
  type: "POV_RESULT";
  playerId: string;
  username?: string;
}

export interface GameFinishedPayload extends BaseSystemPayload {
  type: "GAME_FINISHED";
  placements: { place: number; playerId: string; username?: string }[];
}

export type SystemMessagePayload =
  | DayChangePayload
  | NominationPayload
  | VoteResultPayload
  | PlayerEliminatedPayload
  | DropSpawnPayload
  | HealthChangePayload
  | PovResultPayload
  | GameFinishedPayload;

/** JSON prefix for structured system messages in body */
export const SYSTEM_MSG_PREFIX = "[SYSMSG:";

/** Parse structured system message from body. Returns null if not a structured message. */
export function parseStructuredSystemMessage(body: string): SystemMessagePayload | null {
  if (!body.startsWith(SYSTEM_MSG_PREFIX)) return null;
  const end = body.indexOf("]");
  if (end === -1) return null;
  try {
    const json = body.slice(SYSTEM_MSG_PREFIX.length, end);
    return JSON.parse(json) as SystemMessagePayload;
  } catch {
    return null;
  }
}
