-- Enable RLS on all public tables exposed to PostgREST.
-- This app uses Prisma (DB owner / bypasses RLS) for all access — no client
-- Supabase/PostgREST policies are needed. With RLS on and zero policies,
-- anon/authenticated API roles cannot read or write these tables.
-- Do NOT use FORCE ROW LEVEL SECURITY (would break Prisma as table owner).

ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Auction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuctionBid" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CastingDayResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CastingDropEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CastingDropOption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CastingVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ColorLevel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CommentVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Design" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DesignComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DesignCommentVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DesignOwner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DesignVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DirectMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Enrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EvictionVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Friendship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Game" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GamePlayer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GamePmMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JuryVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MessageReaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Nomination" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PostVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RankingVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RegagedShopItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RegagedShopPurchase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RookiesBet" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RoundResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SimilarNameAlert" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupportMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserColor" ENABLE ROW LEVEL SECURITY;
