-- AlterTable
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeAWeather" TEXT NOT NULL DEFAULT 'SUN';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeBWeather" TEXT NOT NULL DEFAULT 'SUN';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeAGatherReadyAt" TIMESTAMP(3);
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeBGatherReadyAt" TIMESTAMP(3);
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeARainUntil" TIMESTAMP(3);
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeBRainUntil" TIMESTAMP(3);
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeAFireUntil" TIMESTAMP(3);
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeBFireUntil" TIMESTAMP(3);

ALTER TABLE "GamePlayer" ADD COLUMN IF NOT EXISTS "lastGatherAt" TIMESTAMP(3);
