-- AlterTable
ALTER TABLE "User" ADD COLUMN     "bodyColor" TEXT NOT NULL DEFAULT '#F1C27D',
ADD COLUMN     "bodyStyle" TEXT NOT NULL DEFAULT 'body1',
ADD COLUMN     "eyeColor" TEXT NOT NULL DEFAULT '#2E7DFF',
ADD COLUMN     "eyesStyle" TEXT NOT NULL DEFAULT 'eyes1',
ADD COLUMN     "hairColor" TEXT NOT NULL DEFAULT '#2B1B0E',
ADD COLUMN     "hairStyle" TEXT NOT NULL DEFAULT 'hair1',
ADD COLUMN     "mouthStyle" TEXT NOT NULL DEFAULT 'mouth1',
ADD COLUMN     "shirtColor" TEXT NOT NULL DEFAULT '#E53935',
ADD COLUMN     "shirtStyle" TEXT NOT NULL DEFAULT 'shirt1';
