-- AlterEnum: add SURVIVOR / SURVIVOR_BOT (run once; ignore if already present)
DO $$ BEGIN
  ALTER TYPE "GameType" ADD VALUE 'SURVIVOR';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TYPE "GameType" ADD VALUE 'SURVIVOR_BOT';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Game survivor fields
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "survivorPhase" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeAFood" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeAWater" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeAFire" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeBFood" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeBWater" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "tribeBFire" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "survivorMerged" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "losingTribe" TEXT;

-- GamePlayer survivor fields
ALTER TABLE "GamePlayer" ADD COLUMN IF NOT EXISTS "tribe" TEXT;
ALTER TABLE "GamePlayer" ADD COLUMN IF NOT EXISTS "food" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "GamePlayer" ADD COLUMN IF NOT EXISTS "water" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "GamePlayer" ADD COLUMN IF NOT EXISTS "hasImmunity" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "GamePlayer" ADD COLUMN IF NOT EXISTS "sittingOut" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "GamePlayer" ADD COLUMN IF NOT EXISTS "challengeScore" INTEGER NOT NULL DEFAULT 0;

-- RookiesBet
CREATE TABLE IF NOT EXISTS "RookiesBet" (
    "id" TEXT NOT NULL,
    "gameId" TEXT NOT NULL,
    "betterUserId" TEXT NOT NULL,
    "targetUserId" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "paidOutAt" TIMESTAMP(3),
    "payoutAmount" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "RookiesBet_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "RookiesBet_gameId_betterUserId_key" ON "RookiesBet"("gameId", "betterUserId");
CREATE INDEX IF NOT EXISTS "RookiesBet_gameId_idx" ON "RookiesBet"("gameId");
CREATE INDEX IF NOT EXISTS "RookiesBet_betterUserId_idx" ON "RookiesBet"("betterUserId");

DO $$ BEGIN
  ALTER TABLE "RookiesBet" ADD CONSTRAINT "RookiesBet_gameId_fkey"
    FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
